dubbo:
  scan:
    base-packages: com.alibaba.cloud.youxia
  protocol:
    name: dubbo
    port: 26567
  registry:
    address: nacos://127.0.0.1:8848
  cloud:
    subscribed-services: use-redisson-distribute-lock-spring-cloud-alibaba
spring:
  application:
    name: call-distribute-server-cloud-alibaba
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: c7ba173f-29e5-4c58-ae78-b102be11c4f9
        group: DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848
        namespace: c7ba173f-29e5-4c58-ae78-b102be11c4f9
        extension-configs:
          - data-id: call.distribute.server.cloud.alibaba.properties
            group: call-distribute-server-cloud-alibaba
            namespace: c7ba173f-29e5-4c58-ae78-b102be11c4f9
            refresh: true
server:
  port: 8040
