spring:
  cloud:
    gateway:
      routes:
        - id: user_api_route
          uri: http://127.0.0.1:28089
          predicates:
              - Path=/user/getUserInfo
      httpserver:
        wiretap: true